
%%title: Operator Authentication

flowchart TD

%%style

%%External entities or services

gsaoperators((Operators))


subgraph GSA Auth
  gsaauth{GSA Auth}
end

%%Accreditation boundary

subgraph Cloud.gov
  UAA[UAA]
  IdentityCenter[AWS Identity Center]
end

%%Connections

gsaoperators -.auth.-> UAA
UAA -.auth.-> gsaauth
gsaoperators -.auth.-> IdentityCenter
IdentityCenter -.auth.-> gsaauth