graph LR

exposed[CloudFront exposed to public traffic]
behind[CloudFront behind Perimiter account]

click exposed "https://github.com/MyNameIsMissing/cloud-diagrams/blob/main/cloudfront-data-path1.mmd"
click behind "https://github.com/MyNameIsMissing/cloud-diagrams/blob/main/cloudfront-data-path2.mmd"

