---
title: CloudFront Data Path 1
theme: base
config:
  layout: elk
  elk:
    mergeEdges: true
---

flowchart TB

%%External entities or services
customer{Web App Customers}
admin{System Administrators}

%%Accreditation boundary
subgraph Cloud PaaS
  subgraph AWS Commercial Org
    subgraph Commercial Web Access Account
      cloudfront[CloudFront]
      awsnetfirewallWeb[AWS Network Firewall<br>AWS WAF<br>AWS Shield Advanced]
    end
    subgraph Commercial Perimeter Account
      awsEndpointCom[AWS UI or CLI Endpoint]
      awsnetfirewallPer[AWS Network Firewall<br>AWS WAF<br>AWS Shield Advanced]
      awsXit[AWS Transit Gateway]
    end
  end

  subgraph AWS GovCloud Org
    subgraph GovCloud Perimeter Account
      awsEndpointGov[AWS UI or CLI Endpoint]
      awsnetfirewallGov[AWS Network Firewall<br>AWS WAF<br>AWS Shield Advanced]
      awsXitGov[AWS Transit Gateway]
      albForwarderGov[ALB Forwarder]
    end
    subgraph Prod Accounts
      subgraph VPC Prod Workload
        wALB1[Application Load Balancer]
        workload1{Workload}
      end
    end
  end
end

%%Connections
customer -->|HTTPS 443| cloudfront -->|HTTPS 443| albForwarderGov -->|HTTPS 443| wALB1 -->|HTTPS 443| workload1
admin -->|Web or CLI| awsEndpointCom
admin -->|Web or CLI| awsEndpointGov




