---
title: Generic PaaS Architecture
theme: base
config:
  layout: elk
  elk:
    mergeEdges: true
---

flowchart TB

%%External entities or services
customer{Web App Customers}
admin{System Administrators}

%%Accreditation boundary
subgraph Cloud PaaS
  subgraph AWS Commercial Org
    subgraph Web Access Account
      route53[Route 53]
      cloudfront[CloudFront]
    end
    subgraph Commercial Transit Account
      awsnetfirewall[AWS Network Firewall]
      awsXit[AWS Transit Gateway]
    end
  end
  subgraph AWS GovCloud Org
    subgraph Prod Accounts
      ALB[Application Load Balancer]
      appContainer{Web Front End}
      auth[Authentication Service]
    end
    subgraph Security
      vulnScanner[Vulnerability Scanners]
      logging[Centralized Logging]
    end
    subgraph Transit
      awsXitG[AWS Transit Gateway]
      awsnetfirewallG[AWS Network Firewall]
    end
    subgraph Orchestration
      orchestrator[Platform Orchestrator Tools]
    end
    subgraph Dev and Stage
      devResources[Dev Resources]
      stageResources[Staging Resources]
    end
  end
end

%%Connections
customer -->|HTTPS 443| cloudfront -->|HTTPS 443| ALB -->|HTTPS 443| appContainer
admin -->|Web or CLI| awsnetfirewall --> awsXit --> awsXitG
awsXitG --> orchestrator
orchestrator --> devResources & stageResources & appContainer
Security -.audits.-> devResources & stageResources & appContainer
