name: Checks

on:
  push:
    paths:
      - javascriptapp/**
  pull_request:
    paths:
      - javascriptapp/**
      - mermaid_diagrams/**/*.mmd

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: javascriptapp
        run: npm install

      - name: Run tests with coverage
        working-directory: javascriptapp
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: npm test

  validate-mermaid:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Find and validate Mermaid diagrams
        run: |
          for file in $(find mermaid_diagrams -name '*.mmd'); do
            echo "Validating $file"
            mmdc -i "$file" -o /dev/null || exit 1
          done
