name: Checks

on:
  push:
    paths:
      - javascriptapp/**
  pull_request:
    paths:
      - javascriptapp/**

# Restrict permissions to minimum required (fixes zizmor excessive-permissions)
permissions:
  contents: read # Only read access to repository contents

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: javascriptapp
        run: npm install

      - name: Run tests with coverage
        working-directory: javascriptapp
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: npm test
